### ISSUE TITLE
Add delimiter option.

### ISSUE THREAD

**Issue by nedSaf** [amitaibu/drupalCsvToSql#19]
@HelenaEksler Maybe we should add the option for the user to add a custom delimiter if they have something other than `","` in their csv file, What do you think ?

Assign to me if you agree.

**Comment by HelenaEksler** [comment]
I agree. Also columns could be enclosed with other symbol, not with `"`.

![selection_019](https://cloud.githubusercontent.com/assets/8306902/14450163/28ead4c4-0084-11e6-9862-ab4936d4832a.png)
