### ISSUE TITLE
Add a command to return the current version

### ISSUE THREAD

**Issue by ordavidil** [amitaibu/drupalCsvToSql#30]

**Comment by amitaibu** [comment]
Why? This is not typical in any other drush command I know of.

**Comment by ordavidil** [comment]
During the installation of the backoffice I had the same problem of versioning I had in circuit-bid only this time it was with `csv2sql`. On my local I had the `8.x` while the backoffice expect the `7.x`, and it took too long to realize this was the problem.
A simple validation of the available version of `csv2sql` could save a lot of time.

**Comment by amitaibu** [comment]
IMO a proper way would be to download with composer, and execute locally. (The way it's working for example with drush in https://github.com/drupal-composer/drupal-project )

In general I think global packages aren't right.

**Comment by ordavidil** [comment]
sure
